### ISSUE TITLE
Increase Size of Webinar Thumbnail

### ISSUE THREAD

**Issue by thisisayush** [asetalias/aliasandroidapp#11]
Expand Video Thumbnail to at least 80% of the container width with the title below it.

**Comment by thisisayush** [comment]
@jayantb95 Upload Screenshot to verify if this is resolved.

**Comment by jayantb95** [comment]
updated the screenshots @thisisayush 
![communityfragment](https://user-images.githubusercontent.com/11771718/34324863-b0f8a09c-e8a6-11e7-9d86-ec1887bebe8e.png)
![eventfragment](https://user-images.githubusercontent.com/11771718/34324864-b19119bc-e8a6-11e7-962b-848da88009ba.png)
![webinarfragment](https://user-images.githubusercontent.com/11771718/34324865-b1fa3082-e8a6-11e7-9c98-114411c8500e.png)

**Comment by thisisayush** [comment]
The Webinars UI can be made better. With full width Image on top followed by title and description. What say?

**Comment by jayantb95** [comment]
Yes it can be done

**Comment by jayantb95** [comment]
@thisisayush 
issue fixed: image covering the full width of the parent.
screenshots with the latest changes are included in the README.md file

**Comment by thisisayush** [comment]
@jayantb95 Seems good, pack and upload the updated APK so others can test.
