### ISSUE TITLE
Remove Settings Button in Menu

### ISSUE THREAD

**Issue by thisisayush** [asetalias/aliasandroidapp#12]
The Settings button in Menu redirects to Phone Settings and is unnecessary.

**Comment by thisisayush** [comment]
@jayantb95 Please upload screenshot to verify if this is resolved.

**Comment by jayantb95** [comment]
Will upload it once i reach home.

**Comment by jayantb95** [comment]
updated the screenshots @thisisayush 
![communityfragment](https://user-images.githubusercontent.com/11771718/34324863-b0f8a09c-e8a6-11e7-9d86-ec1887bebe8e.png)
![eventfragment](https://user-images.githubusercontent.com/11771718/34324864-b19119bc-e8a6-11e7-962b-848da88009ba.png)
![webinarfragment](https://user-images.githubusercontent.com/11771718/34324865-b1fa3082-e8a6-11e7-9c98-114411c8500e.png)

**Comment by thisisayush** [comment]
Screenshots successfully verifies removal of settings button. Closing the issue now.
